/**
 * Column helpers shared by every table so the Postgres → SQLite mapping is
 * written once. Column names are explicit (snake_case) because the drizzle
 * 1.0 rc `effect-d1` / `d1` drivers ignore `casing` and would otherwise emit
 * camelCase identifiers that disagree with drizzle-kit's generated DDL.
 */
import { integer, text } from "drizzle-orm/sqlite-core";

/** Text primary key generated in the Worker; D1 has no uuid type or default. */
export const id = () =>
  text()
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());

/** Epoch-millisecond timestamp, always UTC, exposed as a `Date`. */
export const timestampMs = (name: string) =>
  integer(name, { mode: "timestamp_ms" });

/** SQLite has no boolean; stored as 0/1, exposed as `boolean`. */
export const bool = (name: string) => integer(name, { mode: "boolean" });

/** JSON stored as text, typed at the column. Validation happens at the boundary. */
export const json = <T>(name: string) =>
  text(name, { mode: "json" }).$type<T>();

/**
 * `createdAt` set on insert and `updatedAt` refreshed on every update, both
 * generated by drizzle in the Worker (replaces Postgres `now()`).
 */
export const timestamps = () => ({
  createdAt: timestampMs("created_at")
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: timestampMs("updated_at").$onUpdateFn(() => new Date()),
});
