/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as ChangelogRouteImport } from "./routes/changelog";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as FaqRouteImport } from "./routes/faq";
import { Route as PricingRouteImport } from "./routes/pricing";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as DotwellKnownForgeHealthRouteImport } from "./routes/[.]well-known.forge-health";
import { Route as AdminIndexRouteImport } from "./routes/admin.index";
import { Route as AdminUsersRouteImport } from "./routes/admin.users";
import { Route as ApiSplatRouteImport } from "./routes/api.$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as ApiWebhooksStripeRouteImport } from "./routes/api.webhooks.stripe";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const ChangelogRoute = ChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any);
const FaqRoute = FaqRouteImport.update({
  id: "/faq",
  path: "/faq",
  getParentRoute: () => rootRouteImport,
} as any);
const PricingRoute = PricingRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const DotwellKnownForgeHealthRoute = DotwellKnownForgeHealthRouteImport.update({
  id: "/.well-known/forge-health",
  path: "/.well-known/forge-health",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any);
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any);
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: "/api/$",
  path: "/api/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: "/api/webhooks/stripe",
  path: "/api/webhooks/stripe",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/changelog": typeof ChangelogRoute;
  "/contact": typeof ContactRoute;
  "/faq": typeof FaqRoute;
  "/pricing": typeof PricingRoute;
  "/privacy": typeof PrivacyRoute;
  "/settings": typeof SettingsRoute;
  "/terms": typeof TermsRoute;
  "/.well-known/forge-health": typeof DotwellKnownForgeHealthRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/api/$": typeof ApiSplatRoute;
  "/admin/": typeof AdminIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/webhooks/stripe": typeof ApiWebhooksStripeRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/changelog": typeof ChangelogRoute;
  "/contact": typeof ContactRoute;
  "/faq": typeof FaqRoute;
  "/pricing": typeof PricingRoute;
  "/privacy": typeof PrivacyRoute;
  "/settings": typeof SettingsRoute;
  "/terms": typeof TermsRoute;
  "/.well-known/forge-health": typeof DotwellKnownForgeHealthRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/api/$": typeof ApiSplatRoute;
  "/admin": typeof AdminIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/webhooks/stripe": typeof ApiWebhooksStripeRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/changelog": typeof ChangelogRoute;
  "/contact": typeof ContactRoute;
  "/faq": typeof FaqRoute;
  "/pricing": typeof PricingRoute;
  "/privacy": typeof PrivacyRoute;
  "/settings": typeof SettingsRoute;
  "/terms": typeof TermsRoute;
  "/.well-known/forge-health": typeof DotwellKnownForgeHealthRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/api/$": typeof ApiSplatRoute;
  "/admin/": typeof AdminIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/webhooks/stripe": typeof ApiWebhooksStripeRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/changelog"
    | "/contact"
    | "/faq"
    | "/pricing"
    | "/privacy"
    | "/settings"
    | "/terms"
    | "/.well-known/forge-health"
    | "/admin/users"
    | "/api/$"
    | "/admin/"
    | "/api/auth/$"
    | "/api/webhooks/stripe";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/changelog"
    | "/contact"
    | "/faq"
    | "/pricing"
    | "/privacy"
    | "/settings"
    | "/terms"
    | "/.well-known/forge-health"
    | "/admin/users"
    | "/api/$"
    | "/admin"
    | "/api/auth/$"
    | "/api/webhooks/stripe";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/changelog"
    | "/contact"
    | "/faq"
    | "/pricing"
    | "/privacy"
    | "/settings"
    | "/terms"
    | "/.well-known/forge-health"
    | "/admin/users"
    | "/api/$"
    | "/admin/"
    | "/api/auth/$"
    | "/api/webhooks/stripe";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRouteWithChildren;
  ChangelogRoute: typeof ChangelogRoute;
  ContactRoute: typeof ContactRoute;
  FaqRoute: typeof FaqRoute;
  PricingRoute: typeof PricingRoute;
  PrivacyRoute: typeof PrivacyRoute;
  SettingsRoute: typeof SettingsRoute;
  TermsRoute: typeof TermsRoute;
  DotwellKnownForgeHealthRoute: typeof DotwellKnownForgeHealthRoute;
  ApiSplatRoute: typeof ApiSplatRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/changelog": {
      id: "/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof ChangelogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/faq": {
      id: "/faq";
      path: "/faq";
      fullPath: "/faq";
      preLoaderRoute: typeof FaqRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pricing": {
      id: "/pricing";
      path: "/pricing";
      fullPath: "/pricing";
      preLoaderRoute: typeof PricingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/.well-known/forge-health": {
      id: "/.well-known/forge-health";
      path: "/.well-known/forge-health";
      fullPath: "/.well-known/forge-health";
      preLoaderRoute: typeof DotwellKnownForgeHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/": {
      id: "/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/admin/users": {
      id: "/admin/users";
      path: "/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AdminUsersRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/api/$": {
      id: "/api/$";
      path: "/api/$";
      fullPath: "/api/$";
      preLoaderRoute: typeof ApiSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/webhooks/stripe": {
      id: "/api/webhooks/stripe";
      path: "/api/webhooks/stripe";
      fullPath: "/api/webhooks/stripe";
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  DotwellKnownForgeHealthRoute: DotwellKnownForgeHealthRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
