/**
 * Renders docs/API_AUTH.md, the credential matrix, from `AppApi` itself
 * (`HttpApi.reflect` through `inspectApi`), so the document cannot drift from
 * the contract. `pnpm -F @gmacko/domain docs:api-auth` rewrites it; the
 * api-auth-matrix test fails when the committed file is stale.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

import type { HttpApi } from "effect/unstable/httpapi";

import { AppApi } from "../src/api";
import { type EndpointInfo, inspectApi } from "../src/inspect";

export const API_AUTH_PATH = fileURLToPath(
  new URL("../../../docs/API_AUTH.md", import.meta.url),
);

const GROUP_ORDER = ["health", "auth", "posts", "settings", "admin"] as const;

const cell = (value: string) => value.replaceAll("|", "\\|");

const row = (info: EndpointInfo): string =>
  `| ${[
    info.group,
    `\`${info.id}\``,
    info.method,
    `\`${cell(info.path)}\``,
    info.credential === "public" ? "public" : `\`${info.credential}\``,
    info.scope ?? "—",
    info.roles.length > 0 ? info.roles.map((r) => `\`${r}\``).join(", ") : "—",
    String(info.successStatus),
    info.errors.length > 0
      ? info.errors.map((e) => `${e.status} \`${e.tag}\``).join(", ")
      : "—",
  ].join(" | ")} |`;

export const renderApiAuthMatrix = (
  api: HttpApi.Top = AppApi as unknown as HttpApi.Top,
): string => {
  const rows = [...inspectApi(api)].sort(
    (a, b) =>
      GROUP_ORDER.indexOf(a.group as (typeof GROUP_ORDER)[number]) -
      GROUP_ORDER.indexOf(b.group as (typeof GROUP_ORDER)[number]),
  );
  const counts = GROUP_ORDER.map(
    (group) => `${group} ${rows.filter((r) => r.group === group).length}`,
  ).join(", ");
  const publicRows = rows.filter((r) => r.credential === "public").length;
  const lines = [
    "# API authentication matrix",
    "",
    "<!-- Generated by packages/domain/scripts/api-auth-matrix.ts from AppApi. Do not edit by hand:",
    "     run `pnpm -F @gmacko/domain docs:api-auth`. The api-auth-matrix test fails when this file is stale. -->",
    "",
    "Every endpoint of `AppApi` (`packages/domain/src/api.ts`) names the credential it accepts. This table is",
    "read back out of the contract with `HttpApi.reflect`, so it is the contract, not a description of it.",
    "",
    `${rows.length} endpoints (${counts}); ${publicRows} public.`,
    "",
    "## Credentials",
    "",
    "| Credential | Accepts | Refuses with |",
    "| --- | --- | --- |",
    "| public | anything, including no credential | — |",
    "| `Session` | the better-auth session cookie (`better-auth.session_token`, `__Secure-` prefixed over https); on non-GET requests only when `Origin` is on the allowlist | 401 `Unauthorized` (no or invalid session), 403 `Forbidden(origin)`, 403 `Forbidden(scope)` for a bearer key |",
    "| `SessionOrKey(scope)` | the session cookie as above, **or** `Authorization: Bearer gmk_…` whose permissions include `scope` or `admin` | 401 `Unauthorized` (invalid, expired or revoked key: no fall-through to the cookie), 403 `Forbidden(scope)` (key lacks the scope), 403 `Forbidden(origin)` |",
    "",
    "Role middlewares run inside the credential middleware and read the `CurrentUser` it provided:",
    "",
    "| Role check | Requires | Refuses with |",
    "| --- | --- | --- |",
    '| `AdminOnly` | `user.role === "admin"`, read fresh (never from the cookie cache). A key\'s `admin` scope does not grant it. | 403 `Forbidden(role)` |',
    "| `WorkspaceRole(min)` | at least `min` (owner > admin > member) in the caller's current workspace | 403 `Forbidden(role)` |",
    "",
    "Rules of thumb: reads take `SessionOrKey(read)`, mutations `SessionOrKey(write)`, deletes `SessionOrKey(delete)`,",
    "everything under `/api/admin` `SessionOrKey(admin)` + `AdminOnly`. Minting and revoking API keys takes",
    "`SessionOrKey(admin)` so the operator CLI and MCP server can manage keys with a key. Deleting the account and",
    "completing bootstrap are `Session` only: a leaked key must never reach them.",
    "",
    "## Endpoints",
    "",
    "| Group | Endpoint | Method | Path | Credential | Key scope | Roles | Success | Errors |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows.map(row),
    "",
  ];
  return lines.join("\n");
};

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  writeFileSync(API_AUTH_PATH, renderApiAuthMatrix());
  process.stdout.write(`wrote ${API_AUTH_PATH}\n`);
}
