-- Generated by `pnpm -F @gmacko/db seed:sql` from src/seed.ts. Do not edit.
-- DESTRUCTIVE: empties every table. Preview and local only.
-- Children before parents, so no foreign key is tripped.
delete from "account";
delete from "api_keys";
delete from "application_settings";
delete from "billing_plan_limit";
delete from "workspace_subscription";
delete from "billing_plan";
delete from "post";
delete from "rate_limit_window";
delete from "session";
delete from "workspace_usage_rollup";
delete from "usage_meter";
delete from "user_preferences";
delete from "waitlist_entry";
delete from "workspace_invite_allowlist";
delete from "workspace_membership";
delete from "workspace";
delete from "user";
delete from "verification";
